from enum import Enum 

class ResponseSignal(Enum):
        FILE_VALIDATED_SUCCESS  = "FILE VALIDATED SUCCESSFULLY"
        FILE_TYPE_NOT_SUPPORTED = "FILE TYPE NOT SUPPORTED"
        FILE_SIZE_EXCEEDED      = "FILE SIZE EXCEEDED"
        FILE_UPLOAD_SUCCESS     = "FILE UPLOAD SUCCESS"
        FILE_UPLOAD_FAILED      = "FILE UPLOAD FAILED"      
        FILE_PROCESSING_FAILED  = "FILE PROCESSING FAILED"
        FILE_PROCESSING_SUCCESS = "FILE PROCESSING SUCCESS"
        NO_FILES_ERROR          = "NO files found "
        FILE_ID_ERROR           = "No FILE FOUND WITH THIS ID "