from enum import Enum 

class ResponseSignal(Enum):
        FILE_VALIDATED_SUCCESS  = "FILE VALIDATED SUCCESSFULLY"
        FILE_TYPE_NOT_SUPPORTED = "FILE TYPE NOT SUPPORTED"
        FILE_SIZE_EXCEEDED      = "FILE SIZE EXCEEDED"
        FILE_UPLOAD_SUCCESS     = "FILE UPLOAD SUCCESS"
        FILE_UPLOAD_FAILED      = "FILE UPLOAD FAILED"      